# Generated by Django 5.2.9 on 2025-12-26 19:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('torrents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('config_type', models.CharField(choices=[('global', 'Global Setting'), ('user_class', 'User Class Setting'), ('torrent', 'Torrent Setting'), ('security', 'Security Setting')], default='global', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('user_ban', 'User Ban'), ('user_unban', 'User Unban'), ('credit_adjust', 'Credit Adjustment'), ('torrent_remove', 'Torrent Removal'), ('invite_create', 'Invite Creation'), ('system_config', 'System Configuration')], max_length=20)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('target_torrent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='torrents.torrent')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['admin', '-timestamp'], name='admin_panel_admin_i_4fd5ac_idx'), models.Index(fields=['action_type'], name='admin_panel_action__d2a3be_idx'), models.Index(fields=['target_user'], name='admin_panel_target__a8e49a_idx')],
            },
        ),
    ]
