# Generated by Django 5.2.9 on 2025-12-26 19:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_hash', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('size', models.BigIntegerField()),
                ('files_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_private', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('piece_length', models.IntegerField(blank=True, null=True)),
                ('pieces_hash', models.TextField(blank=True)),
                ('announce_url', models.URLField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('created_by_client', models.CharField(blank=True, max_length=100)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_torrents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer_id', models.CharField(max_length=40)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('uploaded', models.BigIntegerField(default=0)),
                ('downloaded', models.BigIntegerField(default=0)),
                ('left', models.BigIntegerField()),
                ('state', models.CharField(choices=[('started', 'Started'), ('stopped', 'Stopped'), ('completed', 'Completed')], default='started', max_length=10)),
                ('is_seeder', models.BooleanField(default=False)),
                ('first_announced', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_announced', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peers', to=settings.AUTH_USER_MODEL)),
                ('torrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peers', to='torrents.torrent')),
            ],
            options={
                'ordering': ['-last_announced'],
            },
        ),
        migrations.CreateModel(
            name='TorrentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeders', models.IntegerField(default=0)),
                ('leechers', models.IntegerField(default=0)),
                ('completed', models.IntegerField(default=0)),
                ('total_uploaded', models.BigIntegerField(default=0)),
                ('total_downloaded', models.BigIntegerField(default=0)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('torrent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='torrents.torrent')),
            ],
        ),
        migrations.AddIndex(
            model_name='torrent',
            index=models.Index(fields=['info_hash'], name='torrents_to_info_ha_c9cc27_idx'),
        ),
        migrations.AddIndex(
            model_name='torrent',
            index=models.Index(fields=['created_by'], name='torrents_to_created_046468_idx'),
        ),
        migrations.AddIndex(
            model_name='torrent',
            index=models.Index(fields=['is_active'], name='torrents_to_is_acti_977b82_idx'),
        ),
        migrations.AddIndex(
            model_name='torrent',
            index=models.Index(fields=['category'], name='torrents_to_categor_d702e3_idx'),
        ),
        migrations.AddIndex(
            model_name='peer',
            index=models.Index(fields=['torrent', 'last_announced'], name='torrents_pe_torrent_2ff030_idx'),
        ),
        migrations.AddIndex(
            model_name='peer',
            index=models.Index(fields=['user'], name='torrents_pe_user_id_2dc8ff_idx'),
        ),
        migrations.AddIndex(
            model_name='peer',
            index=models.Index(fields=['ip_address'], name='torrents_pe_ip_addr_656238_idx'),
        ),
        migrations.AddIndex(
            model_name='peer',
            index=models.Index(fields=['is_seeder'], name='torrents_pe_is_seed_14cd20_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='peer',
            unique_together={('torrent', 'user')},
        ),
        migrations.AddIndex(
            model_name='torrentstats',
            index=models.Index(fields=['torrent'], name='torrents_to_torrent_a34f25_idx'),
        ),
        migrations.AddIndex(
            model_name='torrentstats',
            index=models.Index(fields=['-last_updated'], name='torrents_to_last_up_55f85d_idx'),
        ),
    ]
