# Generated by Django 5.2.9 on 2025-12-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrent',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
