# Generated by Django 5.2.9 on 2025-12-26 19:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('torrents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('blocked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('blocked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_ips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.CreateModel(
            name='RateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100)),
                ('limit_type', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0)),
                ('window_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('window_end', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['identifier', 'limit_type'], name='security_ra_identif_b9fe0b_idx'), models.Index(fields=['window_end'], name='security_ra_window__fcf9fa_idx')],
                'unique_together': {('identifier', 'limit_type', 'window_start')},
            },
        ),
        migrations.CreateModel(
            name='AnnounceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=20)),
                ('uploaded', models.BigIntegerField()),
                ('downloaded', models.BigIntegerField()),
                ('left', models.BigIntegerField()),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('peer_id', models.CharField(max_length=40)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('suspicious_reason', models.TextField(blank=True)),
                ('torrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announce_logs', to='torrents.torrent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announce_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='security_an_user_id_87e5d8_idx'), models.Index(fields=['torrent', '-timestamp'], name='security_an_torrent_c28236_idx'), models.Index(fields=['ip_address'], name='security_an_ip_addr_c6bddb_idx'), models.Index(fields=['is_suspicious'], name='security_an_is_susp_439b99_idx'), models.Index(fields=['user', 'timestamp'], name='security_an_user_id_a0b335_idx')],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('fake_upload', 'Fake Upload'), ('abnormal_ratio', 'Abnormal Ratio'), ('announce_flood', 'Announce Flood'), ('ip_spoofing', 'IP Spoofing'), ('invalid_peer_id', 'Invalid Peer ID'), ('token_abuse', 'Token Abuse'), ('ratio_manipulation', 'Ratio Manipulation')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_activities', to=settings.AUTH_USER_MODEL)),
                ('torrent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='torrents.torrent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['user', '-detected_at'], name='security_su_user_id_b29b0b_idx'), models.Index(fields=['activity_type'], name='security_su_activit_ce6b7e_idx'), models.Index(fields=['severity'], name='security_su_severit_4a6d80_idx'), models.Index(fields=['is_resolved'], name='security_su_is_reso_9ef1af_idx')],
            },
        ),
    ]
