# Generated by Django 5.2.9 on 2025-12-26 19:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('torrents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('total_torrents', models.IntegerField(default=0)),
                ('active_torrents', models.IntegerField(default=0)),
                ('total_peers', models.IntegerField(default=0)),
                ('total_upload', models.BigIntegerField(default=0)),
                ('total_download', models.BigIntegerField(default=0)),
                ('total_credit_transacted', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('suspicious_activities', models.IntegerField(default=0)),
                ('blocked_ips', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('ratio_anomaly', 'Ratio Anomaly'), ('credit_threshold', 'Credit Threshold'), ('suspicious_activity', 'Suspicious Activity'), ('system_performance', 'System Performance'), ('security_breach', 'Security Breach')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('torrent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='torrents.torrent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert_type'], name='logging_mon_alert_t_5b1337_idx'), models.Index(fields=['priority'], name='logging_mon_priorit_427caf_idx'), models.Index(fields=['is_acknowledged'], name='logging_mon_is_ackn_8fd50e_idx'), models.Index(fields=['created_at'], name='logging_mon_created_e97207_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10)),
                ('category', models.CharField(choices=[('auth', 'Authentication'), ('tracker', 'Tracker'), ('credit', 'Credit'), ('security', 'Security'), ('admin', 'Admin'), ('system', 'System')], max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['level'], name='logging_mon_level_8215f0_idx'), models.Index(fields=['category'], name='logging_mon_categor_4a82d9_idx'), models.Index(fields=['user'], name='logging_mon_user_id_394b70_idx'), models.Index(fields=['timestamp'], name='logging_mon_timesta_dfc31b_idx'), models.Index(fields=['level', 'category', '-timestamp'], name='logging_mon_level_6a19fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Register'), ('profile_update', 'Profile Update'), ('torrent_upload', 'Torrent Upload'), ('torrent_download', 'Torrent Download'), ('credit_change', 'Credit Change'), ('ban', 'Ban'), ('unban', 'Unban')], max_length=20)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='logging_mon_user_id_b5b5dd_idx'), models.Index(fields=['activity_type'], name='logging_mon_activit_db4231_idx'), models.Index(fields=['ip_address'], name='logging_mon_ip_addr_1e25b8_idx')],
            },
        ),
    ]
